# Generated by Django 4.1 on 2022-08-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_additionalexplanation_rename_notes_note_concepts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='list_of_explanations',
            new_name='additional_explanations',
        ),
    ]
