# Generated by Django 4.1 on 2022-08-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_list_of_explanations_concept_additional_explanations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.topic'),
        ),
    ]
