# Generated by Django 4.1 on 2022-08-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_sub_topic_note_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='concepts',
        ),
    ]
