# Generated by Django 4.1 on 2022-08-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.topic'),
        ),
    ]
