# Generated by Django 4.1 on 2022-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_concept_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='topic',
        ),
        migrations.AddField(
            model_name='concept',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
