# Generated by Django 4.1 on 2022-08-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_concept_topic_concept_notes_alter_note_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='notes',
        ),
        migrations.AddField(
            model_name='concept',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.topic'),
        ),
    ]
