# Generated by Django 4.1 on 2022-08-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_concept_notes_concept_note_alter_note_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='note',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
