# Generated by Django 4.1 on 2022-08-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_rename_note_concept_topic_alter_note_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalexplanation',
            name='examples',
        ),
        migrations.AlterField(
            model_name='concept',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.subtopic'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.note'),
        ),
        migrations.AddField(
            model_name='additionalexplanation',
            name='examples',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
