export const NOTES_LIST_REQUEST = 'NOTES_LIST_REQUEST'
export const NOTES_LIST_SUCCESS = 'NOTES_LIST_SUCCESS'
export const NOTES_LIST_FAIL = 'NOTES_LIST_FAIL'
export const NOTES_LIST_RESET = 'NOTES_LIST_RESET'

export const NOTE_DETAILS_REQUEST = 'NOTE_DETAILS_REQUEST'
export const NOTE_DETAILS_SUCCESS = 'NOTE_DETAILS_SUCCESS'
export const NOTE_DETAILS_FAIL = 'NOTE_DETAILS_FAIL'
export const NOTE_DETAILS_RESET = 'NOTE_DETAILS_RESET'

export const CONCEPT_LIST_REQUEST = 'CONCEPT_LIST_REQUEST'
export const CONCEPT_LIST_SUCCESS = 'CONCEPT_LIST_SUCCESS'
export const CONCEPT_LIST_FAIL = 'CONCEPT_LIST_FAIL'
export const CONCEPT_LIST_RESET = 'CONCEPT_LIST_RESET'

export const CONCEPT_DETAILS_REQUEST = 'CONCEPT_DETAILS_REQUEST'
export const CONCEPT_DETAILS_SUCCESS = 'CONCEPT_DETAILS_SUCCESS'
export const CONCEPT_DETAILS_FAIL = 'CONCEPT_DETAILS_FAIL'
export const CONCEPT_DETAILS_RESET = 'CONCEPT_DETAILS_RESET'

export const CONCEPT_CREATE_REQUEST = 'CONCEPT_CREATE_REQUEST'
export const CONCEPT_CREATE_SUCCESS = 'CONCEPT_CREATE_SUCCESS'
export const CONCEPT_CREATE_FAIL = 'CONCEPT_CREATE_FAIL'
export const CONCEPT_CREATE_RESET = 'CONCEPT_CREATE_RESET'

export const CONCEPT_UPDATE_REQUEST = 'CONCEPT_UPDATE_REQUEST'
export const CONCEPT_UPDATE_SUCCESS = 'CONCEPT_UPDATE_SUCCESS'
export const CONCEPT_UPDATE_FAIL = 'CONCEPT_UPDATE_FAIL'
export const CONCEPT_UPDATE_RESET = 'CONCEPT_UPDATE_RESET'

export const CONCEPT_DELETE_REQUEST = 'CONCEPT_DELETE_REQUEST'
export const CONCEPT_DELETE_SUCCESS = 'CONCEPT_DELETE_SUCCESS'
export const CONCEPT_DELETE_FAIL = 'CONCEPT_DELETE_FAIL'