export const NOTES_LIST_REQUEST = 'NOTES_LIST_REQUEST'
export const NOTES_LIST_SUCCESS = 'NOTES_LIST_SUCCESS'
export const NOTES_LIST_FAIL = 'NOTES_LIST_FAIL'
export const NOTES_LIST_RESET = 'NOTES_LIST_RESET'

export const NOTES_DETAILS_REQUEST = 'NOTES_DETAILS_REQUEST'
export const NOTES_DETAILS_SUCCESS = 'NOTES_DETAILS_SUCCESS'
export const NOTES_DETAILS_FAIL = 'NOTES_DETAILS_FAIL'
export const NOTES_DETAILS_RESET = 'NOTES_DETAILS_RESET'

export const NOTES_CREATE_REQUEST = 'NOTES_CREATE_REQUEST'
export const NOTES_CREATE_SUCCESS = 'NOTES_CREATE_SUCCESS'
export const NOTES_CREATE_FAIL = 'NOTES_CREATE_FAIL'
export const NOTES_CREATE_RESET = 'NOTES_CREATE_RESET'

export const NOTES_UPDATE_REQUEST = 'NOTES_UPDATE_REQUEST'
export const NOTES_UPDATE_SUCCESS = 'NOTES_UPDATE_SUCCESS'
export const NOTES_UPDATE_FAIL = 'NOTES_UPDATE_FAIL'
export const NOTES_UPDATE_RESET = 'NOTES_UPDATE_RESET'

export const NOTES_DELETE_REQUEST = 'NOTES_DELETE_REQUEST'
export const NOTES_DELETE_SUCCESS = 'NOTES_DELETE_SUCCESS'
export const NOTES_DELETE_FAIL = 'NOTES_DELETE_FAIL'